@BASE_URL = http://127.0.0.1:8000/api/v1

###
GET {{BASE_URL}}/chats

###
POST {{BASE_URL}}/files/upload?typeFile=text

###
POST {{BASE_URL}}/chats/input

{
  "input": "puedo tener algun tipo de multa si hago mal mi declaracion de impuesto?",
  "thread_id": "620de18c-a3b2-4443-9d61-1314cd6da1c9"
}